pipeline {
    agent {
        label 'AGENT-1'
    }

    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        
    }

    parameters {
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Select action')
       
    }
    stages {
        stage('init and plan') {
            steps{
                 
                withAWS(region: 'us-east-1', credentials: 'aws-creds'){
                    sh """
                        
                    """
                }
                   
            }
        }
        }

    post {
        always {
            echo " this section always runs"
             deleteDir()
        }

        success {
            echo " this section runs when pipeline is success"
        }
        failure {
            echo " this section runs when pipeline is failed"
        }
    }

}
}